include:
  - project: 's21sec/ci-templates'
    file: 'sast-scan.gitlab-ci.yml'

stages:
  # - build
  - test
  - publish

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  GITLAB_TOKEN: $GITLAB_TOKEN
  GITHUB_TOKEN: $GITHUB_TOKEN
  SCAN_ANNOTATE_PR: "true"
  ENABLE_OSS_RISK: "true"

#scan:
#  stage: test
#  image:
#    name: shiftleft/sast-scan
#  script:
#    - scan --build --src ${CI_PROJECT_DIR} --type credscan,java,yaml,depscan --out_dir ${CI_PROJECT_DIR}/reports
#  rules:
#    - when: always
#  artifacts:
#    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
#    paths:
#      - $CI_PROJECT_DIR/reports/
#    when: always

publish_server:
  image: docker
  stage: publish
  services:
    - docker:dind
    #- docker:19-dind
    #- name: docker:dind
    #  entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]
  script:
    #- export DOCKER_HOST=tcp://gitlab.assist-iot.eu:2375
    #- export DOCKER_HOST=tcp://160.40.53.215:2375
    #- export DOCKER_HOST=tcp://127.0.0.1:2375
    #- export DOCKER_HOST=tcp://localhost:2375
    #- export DOCKER_HOST=tcp://194.30.4.211:2375
    - echo "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest"
    - echo "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA"
    - echo "$CI_REGISTRY_TOKEN"
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    #- docker login $CI_REGISTRY_IMAGE --username $CI_REGISTRY_USER --password-stdin
    - docker build -t $TAG_COMMIT -t $TAG_LATEST -f docker/authz/authzserv/Dockerfile .
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST
  #tags:
  #  - docker

publish_db:
  image: docker
  stage: publish
  services:
    - docker:dind
    #- docker:19-dind
    #- name: docker:dind
    #  entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]
  script:
    #- export DOCKER_HOST=tcp://gitlab.assist-iot.eu:2375
    #- export DOCKER_HOST=tcp://160.40.53.215:2375
    #- export DOCKER_HOST=tcp://127.0.0.1:2375
    #- export DOCKER_HOST=tcp://localhost:2375
    #- export DOCKER_HOST=tcp://194.30.4.211:2375
    - echo "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest"
    - echo "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA"
    - echo "$CI_REGISTRY_TOKEN"
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build 
    #- docker login $CI_REGISTRY_IMAGE --username $CI_REGISTRY_USER --password-stdin
    # - docker build -t $TAG_COMMIT -t $TAG_LATEST -f authzdb/Dockerfile .
    # - docker push $TAG_COMMIT
    # - docker push $TAG_LATEST
  #tags:
  #  - docker
